### PR TITLE
Fix a couple of broken things in metadiags

### PR DESCRIPTION
**Pull request by chaosphere2112**
This fixes some metadata to use what I believe is the "proper" name of "4A" rather than "41", and also makes metadiags a smidgen more forgiving when you specify plotsets.

### CODE REVIEW

**Comment by painter1** [comment]
@mcenerney1 , do you remember why you made it 41?   What I can think of is that maybe it was to make it work with the GUI menu system.

**Comment by mcenerney1** [comment]
At one point the plot set number had to be an int. 4a was a problem. I went to 41 because it was quick & dirty.

**Comment by mcenerney1** [comment]
where is the branch 41_to_4a

**Comment by chaosphere2112** [comment]
@mcenerney1 It's on this repo; sorry, UV-CDAT habit.

**Comment by mcenerney1** [comment]
Which repo? We have too much going on, we'll do this in 2.6

**Comment by chaosphere2112** [comment]
it's on UV-CDAT/uvcmetrics. No rush on getting this merged, I just needed it for my viewer script (which is going to be another pull request).

**Comment by doutriaux1** [comment]
@chaosphere2112 link to this when the viewer PR is ready so that we do not forget

**Pull request closed without merging**
