### PR TITLE
@painter1 was turning off the update but that leads to a double title…

### PR DESCRIPTION
**Pull request by doutriaux1**
… in ps5

### CODE REVIEW

**Comment by doutriaux1** [comment]
@painter1 your new way leads to double title, and the test were passing even though the pix were different, we need to look at a better threshold in another PR


@painter1 here is what your changes did to the ps5:

figure-set5_global_ann_t_plot-combined

**Comment by painter1** [comment]
I think it's ok in my namedtuples branch.  This also fixes up the individual plots in set 5, and does some things better.  So I'll approve this pull request for now, but we can expect to undo it in the near future.

**Comment by doutriaux1** [comment]
notice the difference on the `NCEP`

**Comment by doutriaux1** [comment]
@painter1 it's not ok in master for both @mcenerney1 and I, but reverting your setcolormap fixes it for us.

**Comment by painter1** [comment]
When the update fixes things, that means we are making plots twice, first a bad one, then a good one.  Generally the first one is interfacing to VCS in a more standard way.   When the second one works, it's more by luck than by design.  We need to fix up every case where the update seems to be needed.  I've done that for plot set 5 (where sometimes the first one is good, the second one bad), but probably won't be ready to issue a pull request until I'm back from vacation in mid-September.

**Comment by painter1** [comment]
I ran the automated tests after this change was merged in.  To my surprise, restoring the update() seems to have erased all the gains in running time.  There were other changes too, so I'm not certain.

**Comment by painter1** [comment]
Exceptions are sets 7 (in one direction) and 11,12 (in the other direction).

**Pull request merged**
