### PR TITLE
Add grid file

### PR DESCRIPTION
**Pull request by doutriaux1**
@williams13 @painter1 this is the script ot add grid info so that cdms2 can read it (CF compliant)
I tested it on some data that Qi Tang gave me it works great.

### CODE REVIEW

**Comment by williams13** [comment]
Thanks Charles… Jeff, let’s try this tomorrow. Charles where is the data?

**Comment by doutriaux1** [comment]
@williams13 @painter1 data are on sierra at:
/p/lscratche/cdoutrix/Qi
Qi Tang can see these if you can't so he can probably put them somewhere
on my machine (omar.llnl.gov) they are at:
/home/doutriaux1/Regrid
Tony can get them for you.

**Comment by doutriaux1** [comment]
@williams13 @painter1 example of use:
```
acme_put_grid_in_file -i /home/doutriaux1/Regrid/famipc5_ne120_v0.3_00001.cam.h0.1979-01.nc -g ~/Regrid/ne120np4_pentagons.100310.nc -v Z3
```

**Comment by williams13** [comment]
Thanks..

**Comment by doutriaux1** [comment]
I also put th efiles on my home directory on crunchy

**Pull request merged**
