### PR TITLE
Multidiags

### PR DESCRIPTION
**Pull request by painter1**
This branch and pull request are mainly about Multidiags, a replacement for metadiags.  It merges multiple Options objects and collection names into a list of Options objects, and runs run_diags() (in Python, not as a separate process) to compute all the requested diagnostic plots.

Also, file naming has been substantially improved.

The multidiags branch was branched off the master branch.  But I have, by hand, incorporated the contents of the vertical-reorder branch in this one as well.

### CODE REVIEW

**Comment by mcenerney1** [comment]
Jeff There are conflicts with the master; can you resolve? Thanks.

**Comment by painter1** [comment]
I'll merge the master branch into the multidiags branch, and let you know when it's finished and pushed to github.  It looks like most of the conflicts are in the baselines, but not all.

**Comment by painter1** [comment]
I've resolved the conflicts and run the standard tests.  The merge was easy, mostly deleting obsolete files in the baselines.  One file differed only in a single space, and the other has a bunch of cdscan debugging code in the master branch.  Normally I would delete such code, but I left it in because I have the feeling that we're not finished with cdscan problems.

**Comment by doutriaux1** [comment]
really? we merge w/o tests now...

**Comment by painter1** [comment]
@doutriaux1,  I'm going to issue a pull request soon for multidiags-mp (mp for multiprocessing; this branch is from before I put in multiprocessing).  I'll include a test with that.

**Comment by doutriaux1** [comment]
thanks @painter1 could you also add a test to make sure multi and metadiags give the same answers!

**Pull request merged**
