### PR TITLE
adding conda-forge channel for build to work on Linux

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by mcenerney1** [comment]
PS 4 is not a simple plot.  It computes a "log linear interpolation" on the model and the obs before computing a diff. Also is it possible to clear up this Travis issue today?

**Comment by painter1** [comment]
Why did the baselines have to change?  Is the only change in the mean of the model-obs difference?

**Comment by mcenerney1** [comment]
There was a noticable difference in the diff plot and thought there were changes from ps 5 that had some impact. We'll have to investigate. Getting past the testing issue is important!!

**Comment by doutriaux1** [comment]
the mean of plot set 4a model is now different, but to put it in context it is the same as plot set 4 which looks worng anyway (model mean 237 obs mean 251 mean of difference .4!!!) So Ithink there's an issue in the mean calacualtion somewhere.

**Comment by doutriaux1** [comment]
otherwise the baseline changes are due to the labels being slightly shifted between the two versions of VTK.

**Comment by painter1** [comment]
FYI, the mean of the difference should not be the difference of the means.  That's only true when the (model-obs) difference is a linear operation.  It's not linear if there is any regridding going on, or if model and obs have different missing data masks.

IIRC, NCAR's AMWG assumes that the mean of the difference is the difference of the means.  They probably did this because it avoids a lot of explaining.  But it's often incorrect.

**Comment by mcenerney1** [comment]
Interesting! We'll need to indicate that in the title. Something like "Interpolated Diff"

**Comment by doutriaux1** [comment]
i agree it shouldn't be exactly the same, but a difference of 20K shouldn't become .5K just due to interpolation.

**Comment by painter1** [comment]
In the 4 and 4a plots, I see that the model has a mask over what is the hottest part of the obs data.  The difference calculation would first mask out that obs data, making the effective obs mean much lower.  So I see nothing surprising about the low difference mean.

**Comment by doutriaux1** [comment]
but how can a global mean of 230 and a global mean of 251 can become a global mean of .4K in the difference? It does not make sense.

**Comment by painter1** [comment]
The obs global mean of 251 includes a lot of hot temperatures at sea level in tropical land.  There is no such place (according to the model data).  This obs data has to be masked out.    And note that the things we are subtracting only one horizontal dimension.  The consequence is that the difference operation effectively masks out **all** sea level tropical temperatures.   But that only applies to obs data; the mask had been applied to model data long before.  Excluding all the high temperatures makes the obs mean lower, right?

**Comment by doutriaux1** [comment]
@mcenerney1 @painter1 tes suite passes again. I will let you review my changes to make travis use 2.8 and merge in master. Yeah!

**Pull request merged**
