### PR TITLE
Templatefactory

### PR DESCRIPTION
**Pull request by jccosta**
Updated and tested Template factory for plots in uvcmetrics amwg package.
Tests: https://open.cdash.org/viewTest.php?onlypassed&buildid=4510980
The plot baselines were also updates (as you asked @doutriaux1).

### CODE REVIEW

**Comment by mcenerney1** [comment]
I'm running into a keyword error

IN OCEANIC HEAT TRANSPORT
2: Traceback (most recent call last):
2:   File "/Users/mcenerney1/anaconda/bin/diags", line 848, in <module>
2:     run_diags(o)
2:   File "/Users/mcenerney1/anaconda/bin/diags", line 368, in run_diags
2:     makeplots(res, vcanvas, vcanvas2, varid, fname, plot, package, displayunits=displayunits)
2:   File "/Users/mcenerney1/anaconda/bin/diags", line 474, in makeplots
2:     gmobs, tmobs, tmmobs = return_templates_graphic_methods( vcanvas, gms, ovly, onPage )
2:   File "/Users/mcenerney1/anaconda/lib/python2.7/site-packages/metrics/frontend/it.py", line 68, in return_templates_graphic_methods
2:     disableLegend=disLegend)
2:   File "/Users/mcenerney1/anaconda/lib/python2.7/site-packages/metrics/frontend/templatefactory.py", line 501, in build_templates
2:     template = M.get(legend='local',tname=templateNameArray[i])
2: TypeError: get() got an unexpected keyword argument 'tname'

**Comment by jccosta** [comment]
@mcenerney1 the argument tname in EzTemplate was added to uvcdat int this pull request: https://github.com/UV-CDAT/uvcdat/pull/2087
Are you using the latest version of uvcdat?

**Comment by mcenerney1** [comment]
Which package in uvcdat needs updating. Still getting after these changes
     template = M.get(legend='local',tname=templateNameArray[i])
2: TypeError: get() got an unexpected keyword argument 'tname'

**Comment by jccosta** [comment]
@mcenerney1 EzTemplate is in Packages/vcsaddons (in uvcdat).

**Comment by mcenerney1** [comment]
Update vcsaddons, vcs & vtk. Get new error
   File "/Users/mcenerney1/anaconda/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 1709, in prepLine
2:     colors.InsertNextTypedTuple(vtk_color)
2: AttributeError: 'vtkCommonCorePython.vtkUnsignedCharArray' object has no attribute 'InsertNextTypedTuple'
2: TEST is using metrics version: g9a77c0d templatefactory 1.0

**Comment by jccosta** [comment]
@mcenerney1 I am using the the latest version of uvcdat as @doutriaux1 told me:
conda create -n nightly -c uvcdat/label/nightly -c uvcdat uvcdat hdf5=1.8.16 pyqt=4.11.3
This version has the updated version of EzTemplate with the tname (variable to avoid template name collisions). I didn't get the error you are getting.
@doutriaux1 Some light here? :-)

**Comment by mcenerney1** [comment]
I got past the tname issue.  This one looking for a InsertNextTypedTuple attribute.

**Pull request merged**
