### PR TITLE
Merged new derived variables

### PR DESCRIPTION
**Pull request by painter1**
I have merged the master branch into this branch, and it passed my manual tests as well as the usual automated tests.  This branch, merged-new-derived-variables, has all the features of new-derived-variables but it shouldn't give any grief to the git merge tool.

### CODE REVIEW

**Comment by mcenerney1** [comment]
I'm pulling into my mac and having a problem with 
AttributeError: 'vtkCommonCorePython.vtkUnsignedCharArray' object has no attribute 'InsertNextTypedTuple'
There's a package that needs to be updated but it's not obvious which one.
This is unrelated to metrics. But I'd like to see it pass on my system before the merge.

**Comment by painter1** [comment]
I've not seen that vtk error.  Could you tell me how you got it?  I'd like to try to reproduce it on my Mac.

**Comment by mcenerney1** [comment]
It's under the hood in cnvs2.plot(line, bg=1).  
You probably won't be able to duplicate it.

**Comment by mcenerney1** [comment]
Actually all checks passed.

**Pull request merged**
