### PR TITLE
Ps5 better for chris

### PR DESCRIPTION
**Pull request by mcenerney1**
This branch has repairs to the mean calculation and the name for model or obs from the command line displayed on the graphic.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@mcenerney1 this is still failing, do you know what's going on?

**Comment by mcenerney1** [comment]
tets for meta diags, 5, 6, 7 and 15 fail.  tests for 5, 6, & 7 are cosmetics changes. They are ok. The other 2 are failing for unknown reasons.  I'm looking into them. I think we can give it to Jerry only for testing.

**Comment by mcenerney1** [comment]
baseline file names changed for 15. Now only 5, 6 & 7 fail. They need to be rebaselined.

**Comment by doutriaux1** [comment]
4a and 5 still fail @mcenerney1

**Comment by mcenerney1** [comment]
For test 5 I needed the new netcdf files.  4A now passes;must be the template issue.

**Comment by doutriaux1** [comment]
5 still fails ;)

**Comment by mcenerney1** [comment]
One more time.

**Comment by mcenerney1** [comment]
Yay!!

**Pull request merged**
