### PR TITLE
Templatefactory

### PR DESCRIPTION
**Pull request by jccosta**
Please review the new system for template creation.
At the end of the it.py file there is a commented code that can be used to test the new code and to learn how to use it.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@jccosta this brought the test suite from 3mn to 45mn with some test (diags11) timing out. I'm reverting this. Please hold on until the test suite is fixed before submitting a new PR. At this point I will send instruction on how to run the suite which should always be ran and pass before submitting a PR.

**Comment by doutriaux1** [comment]
@jccosta see: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4259473
vs the one before your merge:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=4259479

**Comment by jccosta** [comment]
Thanks for point it to me, Charles.
I will take a look on what is happening and I will wait for your instructions.

**Comment by doutriaux1** [comment]
Thank you! Hopefully in a few hours.

**Pull request merged**
