### PR TITLE
Susburrows/qflx lhflx conversions

### PR DESCRIPTION
**Pull request by susburrows**
This code to enables comparison of LHFLX (latent heat flux in W/m^2) vs. QFLX (evaporation in mm/day), if only one of them is present in the provided model/obs file.  I added functions in reductions.py to convert QFLX to LHFLX and LHFLX to QFLX, by either multiplying or dividing by the latent heat of vaporization, and converting the units.  Then I added derived_variables in amwg.py.  I assume/believe that the code will look for a derived_variable only if it doesn’t find a variable defined in the file with the name it is looking for.  So I added a QFLX variable and an LHFLX variable.  Now, if it looks for LHFLX in a file and can’t find it, it will look for QFLX and convert it if possible, and vice versa.

It appears to work — see plots below:
setso_ann_lhflx_laryea_s_extratropics-combined
setso_ann_qflx_laryea_s_extratropics-combined

### CODE REVIEW

**Comment by susburrows** [comment]
(the unit conversion and checking could still be made more elegant / robust)

**Comment by susburrows** [comment]
@painter1 @mcenerney1

**Comment by painter1** [comment]
Yes, it's true that if you put your new variable calculations in standard_variables (as I think you did), then the calculations won't be performed if the variables already exist (with the proper name) in the data.

But reductions.py is the wrong place to put your functions.  That file was never meant for more than dimensionality reduction, and even so it's getting too big.  The right place is a new file within packages/amwg/deriviations/.

I hated that ad-hoc code which I put in reductions.py to fix up QFLX.  I forget why it's there, probably an obs set needed it.  Is something else doing that job now?

**Comment by susburrows** [comment]
@painter1 , the functions I added in reductions.py are dedicated functions for converting QFLX and LHFLX using knowledge of the latent heat, and converting between mm/day and kg/m2/day.  So maybe we could use them (adapting them a bit if needed), together with the derived variable definitions, to handle these conversions instead of doing it in convert_units.  Where would you suggest is the best place to put the new functions?

**Comment by susburrows** [comment]
Oops, sorry, I didn't read your comment carefully enough.  I can move them to a new file.  Do you have a suggestion for the name of the new file?  I could just call it qflx_lhflx.py, or something more general.

**Comment by painter1** [comment]
If you look at what's in deriviations/, it's a hodgepodge of names.  So do whatever makes sense to you.

**Comment by susburrows** [comment]
OK, I'll do that and also try to sort out whether I can adapt this so that the code for dealing with QFLX conversions in reductions.py is no longer needed.

**Comment by susburrows** [comment]
@painter1 , I have updated the branch following your suggestion -- I moved the conversions to a new file, derivations/qflx_lhflx_conversions.py.  They are hard-coded, which is a little ugly, but it probably can't be done a great deal more elegantly since there is a need to use physical knowledge to handle these conversions (so udunits alone can't do it).

In amwg.py, I now simply say that LHFLX and QFLX are equivalent variables.

In reductions.reconcile_units, if I detect either a variable name containing LHFLX or QFLX, or a conversion from kg/m2/s to mm/day (which was previously included as a special case in reconcile_units and might not be needed now), I then call the dedicated function from derivations/qflx_lhflx_conversions.py.

**Comment by susburrows** [comment]
Here are the output plots after the update (which look the same as before).  Note that by default I select 'W/m^2' as the units for LHFLX and 'mm/day' as the units for QFLX, which is a it arbitrary, but we have to pick some default behavior and I think this is reasonable.

setso_ann_lhflx_laryea_s_h_land-combined

setso_ann_qflx_laryea_s_h_land-combined

**Comment by susburrows** [comment]
oops, there is still an issue with the LHFLX image ... hang on & I will fix it.

**Comment by susburrows** [comment]
OK, I have updated the branch and replaced the figures in the previous comment with the current output.  I think this code should work reasonably robustly now.

**Comment by painter1** [comment]
LGTM.  Thank you, Susannah!

**Comment by susburrows** [comment]
Great, thanks!

**Pull request merged**
