### PR TITLE
re-updated uvcmetrics.json

### PR DESCRIPTION
**Pull request by doutriaux1**
@painter1 @isubsmith do not merge this in yet. Thanks

### CODE REVIEW

**Comment by isubsmith** [comment]
I would very much like this file to go away and be replaced with programmatically generated templates OR to have someone finally add templates for 7-10 plots per page. Otherwise land diagnostics will never be “complete”…….


On Nov 19, 2015, at 7:02 PM, Robert Jacob <notifications@github.com<mailto:notifications@github.com>> wrote:


@painter1<https://github.com/painter1> @isubsmith<https://github.com/isubsmith> do not merge this in yet. Thanks

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/UV-CDAT/uvcmetrics/pull/131

Commit Summary

  *   re-updated uvcmetrics.json

File Changes

  *   M share/uvcmetrics.json<https://github.com/UV-CDAT/uvcmetrics/pull/131/files#diff-0> (32441)

Patch Links:

  *   https://github.com/UV-CDAT/uvcmetrics/pull/131.patch
  *   https://github.com/UV-CDAT/uvcmetrics/pull/131.diff

**Comment by doutriaux1** [comment]
@isubsmith what's the difference really? It's much easier to tweak the template on a stand alone plot than run the diags to see the result. no?

**Comment by isubsmith** [comment]
The difference between what and what?

I need 7, 8, 9, and 10 plots-per-page support. It makes way more sense to me to do that programmatically rather than modifying this file.

I don’t have the knowledge to do it either way (using EZTemplate I guess OR modifying that file since I have no idea what generated it).

Right now, I’m not concerned with making individual plots look ok (there is a huge amount of work to do that too), just the ability to actually get 7, 8, 9, and 10 plots on one “page”.

Does that make sense?

On Nov 30, 2015, at 1:45 PM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@isubsmith<https://github.com/isubsmith> what's the difference really? It's much easier to tweak the template on a stand alone plot than run the diags to see the result. no?

**Comment by doutriaux1** [comment]
@painter1 ready to be merged in

**Pull request merged**
