### PR TITLE
New derived variables

### PR DESCRIPTION
**Pull request by painter1**
This computes all missing variables of issue 222, except for certain cloud variables which are probably not possible with standard ACME output.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@painter1 I'm running a metadiags run now to test this; I'll let you know if I run across any unexpected issues.

**Comment by mcenerney1** [comment]
Before we merge anything more into master we need the PR "Ps5 better for chris" done first. Several tests fail but this one will give Jerry something to test.  Once that one is done and the tests pass I'll start merging these into master.  On Monday, when Charles gets in we'll start to move.

**Comment by doutriaux1** [comment]
@mcenerney1 did you get your branch to pass the tests? This is priority number 1 before we can move forward.

**Comment by mcenerney1** [comment]
Not yet. The vcs issue is the problem.

**Comment by doutriaux1** [comment]
@mcenerney1 the `vcs` issue was due to a syntax change in the newer `vcs` introduced by @danlipsa I fixed this code to set attributes on 1D plots the new (and proper) way.

**Comment by mcenerney1** [comment]
This branch passes all tests.

**Comment by painter1** [comment]
An automated merger (by git merge...) with the master branch completely ruined this branch.  All my work was gone; there was no past git commit left (containing my work); it was impossible to recover.  This pull request should be revoked, and the branch deleted.  I restored my work from a disk backup system, and created another branch, merged-new-derived-variables, which should be used instead of this one.

**Comment by mcenerney1** [comment]
Back on track. Standby!

**Comment by mcenerney1** [comment]
Is this the same problem?
amwg plot set 13 listvars= ['CLISCCP']

14:     self.plan_computation( model, obs, varnom, seasonid, region, plotparms )

14:   File "/home/travis/miniconda/lib/python2.7/site-packages/metrics/packages/amwg/amwg.py", line 3935, in plan_computation

14:     vid1 = self.var_from_cdv( filetable1, varnom, seasonid, region )

14:   File "/home/travis/miniconda/lib/python2.7/site-packages/metrics/packages/amwg/amwg.py", line 3917, in var_from_cdv

14:     (lambda x,vid,season=self.season,region=region:

14:   File "/home/travis/miniconda/lib/python2.7/site-packages/metrics/packages/amwg/amwg.py", line 423, in commvar2var

14:     inputs = [ availdict[v].id() for v in svd._inputs if v in availdict] + builtin_variables

14: NameError: global name 'builtin_variables' is not defined

**Comment by painter1** [comment]
Yes it is.  That's because you're looking at the wrong branch.  The branch new-derived-variables is broken beyond repair.  Please use the branch merged-new-derived-variables instead.  I'll close this pull request to make the situation more clear.

**Comment by mcenerney1** [comment]
oops!

**Comment by painter1** [comment]
Please don't re-open this pull request.  It's fine to delete the branch new-derived-variables too, but I'd rather wait until everything else has been merged and it's all settled down.

**Comment by mcenerney1** [comment]
AGREED!

**Pull request closed without merging**
