### PR TITLE
Logging Conversion

### PR DESCRIPTION
**Pull request by chaosphere2112**
This pull request converts everything that was previously run through `print` to instead use the Python `logging` module. Every module now uses a `logging.Logger` instance made specially for it, which will allow for smarter filtering later down the road (should be able to make only certain modules/packages/whatever print on the console/to a log file). I reviewed many of the logging conversions that Anna did (and added a few myself). The rule of thumb that I used for logging levels was basically this:

**CRITICAL**: Major error that leads to spontaneous demise of software
**ERROR**: Any serious error that results in aborting whatever task we're working on
**WARNING**: Anywhere that a user input was unclear, data might be odd, or anything possibly anomalous is occuring.
**INFO**: Messages that might be useful feedback for a user ("Computing variable X", "Starting Task Y")
**DEBUG**: Basically anything that dumps a value from a variable, or contains all capital letters with lots of asterisks, or anything else that looked vaguely like it was just there for the developer's sake.

I also added two new options to `options.py`: `--log_level` and `--log_file`. `--log_level` takes one of the above mentioned levels (also accepts lowercase), and filters all output that is below that level (Default is to only display errors). `--log_file` specifies a location to write the logging information to (rather than `stdout`).

I also added support to `metadiags` to handle these options gracefully; now, instead of dumping all of the diagnostics output into a big file in a random order, each `diags` run gets its own file in `amwg/DIAGS_OUTPUT/(a hash of the model paths, sorted, and the obs path)/filename_generated_based_on_args.log`. To prevent chatty libraries from dumping their (developer-relevant-only) information into the log, all stdout and stderr are directly routed to `/dev/null` (if a relevant error would show up in that, you are given the command line to directly run the relevant `diags` job so you can see the error message).

This means that metadiags' default stdout now looks something like this:

```
$ metadiags --model path=/Volumes/Storage/climate_output2,climos=yes --obs path=/Volumes/Storage/obs/,climos=yes --package AMWG --outputdir=/Volumes/Storage/diags3 --dsname=my_awesome_diags --set 5
ERROR: Command 
diags --model path=/Volumes/Storage/climate_output2,climos=yes,type=model  --obs path=/Volumes/Storage/obs/,climos=yes,filter="f_startswith('CERES2')" --logo no --colormaps diff=bl_to_darkred model=rainbow obs=rainbow   --package AMWG  --set 5 --seasons DJF --vars ALBEDO  --outputdir /Volumes/Storage/diags3/amwg   --prefix set5 --postfix CERES2  --log_level DEBUG  --log_file /Volumes/Storage/diags3/amwg/DIAGS_OUTPUT/ca201281dc7136a0fe6fa978a5e5eece/AMWG_5_CERES2_ALBEDO_DJF.log
 failed with code of 1. Log file is at /Volumes/Storage/diags3/amwg/DIAGS_OUTPUT/ca201281dc7136a0fe6fa978a5e5eece/AMWG_5_CERES2_ALBEDO_DJF.log.
... (basically the same for each failure) ...
$ 
```

which you can also pipe into a logfile using the --log_file argument.

I also gave into temptation and deleted every one of the `-old` files or `-new` files or flavors of `metadiags` that I was pretty sure could be safely eliminated (I didn't touch `climatology-old` or `diags-old`, since I've not messed with those before). If you see anything missing or broken, please let me know and I'll restore the file in this pull request.

Big thanks to @pawpepe for getting the bulk of this together!

### CODE REVIEW

**Comment by painter1** [comment]
This was a huge job; thank you Sam and Anna!   Something this big will surely need some tweaks in the future, but the changes I sampled were all done correctly in my opinion.   There is a typo to fix in utilities.py: "exeption" should be "exception".

**Comment by doutriaux1** [comment]
@chaosphere2112 test suite failed

**Comment by doutriaux1** [comment]
@chaosphere2112 diags test 11 did not come back after 10mn. Is there a `raw_input` somewhere?

**Comment by chaosphere2112** [comment]
@painter1 Good catch! I did a mass search for all calls to anything on logger, and found a few other typos. Hopefully that's everything. Let's see how this round of travis testing goes.

**Comment by doutriaux1** [comment]
@chaosphere2112 real fail on travis now.

**Pull request merged**
